### ISSUE TITLE
Package archive 3.2.1 breaks example

### ISSUE THREAD

**Issue by thumbert** [sestegra/spreadsheet_decoder#35]
Hi,

If I run the example/spreadsheet_decoder.dart with archive 3.2.1 I get the error:
```
Unhandled exception:
type 'Null' is not a subtype of type 'List<int>' in type cast
#0      ZipEncoder.getFileCrc32 (package:archive/src/zip_encoder.dart:91:34)
#1      ZipEncoder.addFile (package:archive/src/zip_encoder.dart:136:15)
#2      ZipEncoder.encode (package:archive/src/zip_encoder.dart:65:7)
#3      SpreadsheetDecoder.encode (package:spreadsheet_decoder/src/spreadsheet.dart:175:25)
#4      main (file:///home/adrian/Documents/repos/git/other/spreadsheet_decoder/example/spreadsheet_decoder.dart:34:32)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
Example works with archive version 3.1.10.  Not sure if there is a quick fix or something we should report to the archive package maintainers. 

Thanks,
Tony

**Comment by sestegra** [comment]
@thumbert Thank you for reporting the issue.

See tests report for `example/spreadsheet_decoder.dart` with following `archive` versions.

* 3.1.10 => OK
* 3.1.11 => 0K
* 3.2.0 => OK
* 3.2.1 => Fail

So, the issue seems to be on [archive](https://github.com/brendan-duncan/archive)

**Comment by sestegra** [comment]
Issue fixed on release 2.0.2
